name: devops test

on: 
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: get code from github
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          rm -rf /home/ubuntu/myhtml
          sudo git clone https://github.com/PTCman/myhtml.git
          sudo mv -f myhtml/*.html /var/www/html

      
  
